apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-server
spec:
  gateways:
    - http-server
  hosts:
    - http-server
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: http-server-service-0
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: http-server
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - http-server
      port:
        name: http-server
        number: 80
        protocol: HTTP
