apiVersion: v1
kind: Service
metadata:
  name: http-server-service
  namespace: cncamp
  labels:
    run: http-server
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: http-server